### ISSUE TITLE
Center stick problem

### ISSUE THREAD

**Issue by magyarl89** [wdcossey/SharpPropoPlus#3]
Hi!
Thanks for the release!
Now I had time to try it.

Unfortunately I experiencing the same problem as in SmartPropoPlus:
when I move the stick slightly from the center, and let it go back to center with slow movement, the signal often can't get back to the center precisely, remaining some offset. Then I start to move the stick slightly to the other way and the signal suddenly jumps over the true center point to the new stick position.
I tried to use this anyway in simulators but unfortunately you can't make small and precise movement around the center, it feels bad.

The transmitter sticks are ok. Using the USB connection gives very precise center positions every time (but unfortunately with a low sample rate).
I checked the pulse scope with windows magnifier, and as I can see, it goes to the center precisely every time. Where can be the problem?

**Comment by wdcossey** [comment]
Hi magyarl89,

What sound card are you using in your system? 

You are using the FlySky (Turnigy) i6 radio..?

I have noticed that most sound card drivers have some sort of noise cancelling for microphones, this will screw around with Smart/SharpPropoPlus and cause some issues.

I'm happy to work with you to try resolve the issue you are having.

I will release a new version that will allow you to adjust the PPM settings (they are there just disabled at the moment), maybe look at adjusting the filters to fine tune the updates from the radio to get them a little more precise.

I am away at the moment so I can't test any changes I could make, if you are happy to wait until the 1st/2nd of April, we can get this issue resolved.

**Comment by magyarl89** [comment]
Hi wdcossey,

I use sound card of the motherboard: Realtek ALC889A.
I use the Line-In (not as microphone) and I disabled every sound effect what I found.

My transmitter is FlySky i6S. It has a native USB port as well (this is why I know the sticks are ok).

I'm happy if you are interested in solving this issue :)
Timing is not critical for me, I look forward for the next updates when you have time for that.
Thanks!

**Comment by wdcossey** [comment]
Hi @magyarl89,

I'll release a new update within the next day or two (perhaps tonight if I have time).
This will allow you to adjust the settings (PulseWidth, Separator, Jitter, etc) for the PPM decoders.

Having a look at what @lloydhooson has done (https://github.com/lloydhooson/SharpPropoPlus/commit/03ad6ac55d371b076fabbab0074915f0532a5b36), you should set:
MinPulseWidth -> 189.0
MinaxPulseWidth -> 380.0

But your results may vary and may need further tuning, I'll help you through it once I have committed the changes.

**Comment by wdcossey** [comment]
https://github.com/wdcossey/SharpPropoPlus/releases/tag/v0.9.834.56-beta

@Radrik5

**Comment by magyarl89** [comment]
Hi wdcossey,

Thank you for giving some solution for my PC sim connection problem.

In the meantime I found the perfect solution:
https://github.com/Cleric-K/vJoySerialFeeder
The greatest advantage is that it uses the digital protocol at high update frequency (8ms).
Take a look :)

**Comment by wdcossey** [comment]
Hi @magyarl89 ,

Thanks for the link, I have been looking at it, it's very interesting.

I am actually busy working on an Arduino solution of my own, however since the work done by @Cleric-K is quite comprehensive I may borrow from that solution, I will contact the author in the next few days.

I am working with a DigiSpark ATtiny85 (see: http://digistump.com/products/1), I will see if I can get a solution up and running in the next few days.

![ATtiny85](https://s3.amazonaws.com/digistump-resources/images/m/2520dcf84a0a3bf2257c2559d7a187db.jpg)

Again, thank you for the information provided. :)

**Comment by wdcossey** [comment]
Hi @magyarl89,

Have a look what I have done [flysky-ibus-leonardo](https://github.com/wdcossey/flysky-ibus-leonardo)

No need fo any software to decode signals!
